theme: osuny
enableRobotsTXT: true
removePathAccents: true
pagination:
  pagerSize: 30
params:
  plausible: iut.u-bordeaux-montaigne.fr
  pages:
    index:
      truncate_description: 0
  summary:
    position: hero
  search:
    active: true
  debug:
    productionUrl: "https://www.iut.u-bordeaux-montaigne.fr"
  logo:
    header: "/assets/images/logo.svg"
    footer: "/assets/images/logo.svg"
  organizations:
    single:
      backlinks: true
  persons:
    single:
      backlinks: true