params:
  cdnkey: https://osuny-1b4da.kxcdn.com
  cookie_banner:
    enable: false
baseURL: https://bordeauxmontaigne-iut.netlify.app/
defaultContentLanguage: fr
languageCode: fr
languages:
  fr:
    title: IUT Bordeaux Montaigne
theme: osuny-hugo-theme
paginate: 18
permalinks:
  posts:          /actualites/:year/:month/:day/:slug/
  categories:     /actualites/:slug/
  persons:        /equipe/:slug/
  authors:        /equipe/:slug/actualites/
  administrators: /equipe/:slug/administration/
  researchers:    /equipe/:slug/publications/
  teachers:       /equipe/:slug/formations/
taxonomies:
  administrator:  administrators
  author:         authors
  category:       categories
  researcher:     researchers
  teacher:        teachers
